# Generated by Django 5.1.15 on 2026-06-27 18:35

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Catalogo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("codigo", models.CharField(max_length=80, unique=True)),
                ("nombre", models.CharField(max_length=255)),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("equipo_medico", "Equipo médico"),
                            ("insumo", "Insumo"),
                            ("medicamento", "Medicamento"),
                            ("infraestructura", "Infraestructura"),
                        ],
                        max_length=30,
                    ),
                ),
                ("unidad", models.CharField(default="unidad", max_length=50)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CentroSalud",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("nombre", models.CharField(max_length=255)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("hospital", "Hospital"),
                            ("ambulatorio", "Ambulatorio"),
                            ("modulo_temporal", "Módulo temporal"),
                            ("refugio", "Refugio"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "estado_operativo",
                    models.CharField(
                        choices=[
                            ("operativo", "Operativo"),
                            ("parcial", "Parcial"),
                            ("danado", "Dañado"),
                            ("no_operativo", "No operativo"),
                        ],
                        default="operativo",
                        max_length=30,
                    ),
                ),
                ("geolocalizacion", models.CharField(blank=True, max_length=100)),
                ("estado", models.CharField(max_length=120)),
                ("municipio", models.CharField(max_length=120)),
                ("tiene_electricidad", models.BooleanField(default=False)),
                ("tiene_agua", models.BooleanField(default=False)),
                ("tiene_oxigeno", models.BooleanField(default=False)),
                ("tiene_personal_tecnico", models.BooleanField(default=False)),
                ("contacto_responsable", models.CharField(blank=True, max_length=255)),
                ("ultima_actualizacion", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EventoSincronizado",
            fields=[
                (
                    "idempotency_key",
                    models.UUIDField(primary_key=True, serialize=False),
                ),
                ("entity", models.CharField(max_length=80)),
                ("entity_id", models.UUIDField(blank=True, null=True)),
                ("resultado", models.CharField(max_length=30)),
                ("payload_hash", models.CharField(blank=True, max_length=128)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Organizacion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("nombre", models.CharField(max_length=255)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ong", "ONG"),
                            ("gobierno", "Gobierno"),
                            ("voluntario", "Voluntario"),
                            ("donante_privado", "Donante privado"),
                            ("centro_salud", "Centro de salud"),
                        ],
                        max_length=30,
                    ),
                ),
                ("contacto", models.CharField(blank=True, max_length=255)),
                ("verificada", models.BooleanField(default=False)),
                ("activa", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RegistroAuditoria",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("usuario_id", models.UUIDField(blank=True, null=True)),
                ("accion", models.CharField(max_length=120)),
                ("entidad", models.CharField(max_length=80)),
                ("entidad_id", models.UUIDField(blank=True, null=True)),
                ("detalle", models.JSONField(blank=True, default=dict)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Donacion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("cantidad", models.PositiveIntegerField()),
                (
                    "condicion",
                    models.CharField(
                        choices=[
                            ("nuevo", "Nuevo"),
                            ("usado_funcional", "Usado funcional"),
                            ("requiere_reparacion", "Requiere reparación"),
                            ("requiere_calibracion", "Requiere calibración"),
                        ],
                        max_length=30,
                    ),
                ),
                ("vencimiento", models.DateField(blank=True, null=True)),
                ("certificacion", models.TextField(blank=True)),
                ("ubicacion_actual", models.CharField(blank=True, max_length=100)),
                ("ubicacion_texto", models.CharField(blank=True, max_length=255)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("registrada", "Registrada"),
                            ("disponible", "Disponible"),
                            ("asignada", "Asignada"),
                            ("en_transito", "En tránsito"),
                            ("entregada", "Entregada"),
                            ("en_uso", "En uso"),
                            ("descartada", "Descartada"),
                        ],
                        default="registrada",
                        max_length=20,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="coordinacion.catalogo",
                    ),
                ),
                (
                    "donante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="coordinacion.organizacion",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Asignacion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("cantidad_asignada", models.PositiveIntegerField()),
                (
                    "estado_claim",
                    models.CharField(
                        choices=[
                            ("tentativa", "Tentativa"),
                            ("confirmada", "Confirmada"),
                            ("superada", "Superada"),
                            ("liberada", "Liberada"),
                        ],
                        default="tentativa",
                        max_length=20,
                    ),
                ),
                ("claim_ts_cliente", models.DateTimeField()),
                ("claim_ts_servidor", models.DateTimeField(blank=True, null=True)),
                (
                    "estado_logistico",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("en_transito", "En tránsito"),
                            ("entregada", "Entregada"),
                            ("confirmada", "Confirmada"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                (
                    "donacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="coordinacion.donacion",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Envio",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("preparando", "Preparando"),
                            ("en_transito", "En tránsito"),
                            ("entregado", "Entregado"),
                            ("incidencia", "Incidencia"),
                        ],
                        default="preparando",
                        max_length=20,
                    ),
                ),
                ("responsable", models.CharField(max_length=255)),
                ("foto_confirmacion_ref", models.CharField(blank=True, max_length=500)),
                (
                    "geolocalizacion_entrega",
                    models.CharField(blank=True, max_length=100),
                ),
                ("timestamp_entrega", models.DateTimeField(blank=True, null=True)),
                ("recibido_por", models.CharField(blank=True, max_length=255)),
                ("notas", models.TextField(blank=True)),
                (
                    "asignacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="coordinacion.asignacion",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Necesidad",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("cantidad_solicitada", models.PositiveIntegerField()),
                ("cantidad_cubierta", models.PositiveIntegerField(default=0)),
                (
                    "nivel_triage",
                    models.CharField(
                        choices=[
                            ("1_critico", "1 - Crítico"),
                            ("2_urgente", "2 - Urgente"),
                            ("3_importante", "3 - Importante"),
                            ("4_rutinario", "4 - Rutinario"),
                        ],
                        max_length=20,
                    ),
                ),
                ("requisitos_operacion", models.JSONField(blank=True, default=dict)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("abierta", "Abierta"),
                            ("parcial", "Parcial"),
                            ("cubierta", "Cubierta"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="abierta",
                        max_length=20,
                    ),
                ),
                (
                    "centro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="coordinacion.centrosalud",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="coordinacion.catalogo",
                    ),
                ),
                (
                    "reportada_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="coordinacion.organizacion",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="asignacion",
            name="necesidad",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="coordinacion.necesidad"
            ),
        ),
        migrations.AddField(
            model_name="asignacion",
            name="organizacion_responsable",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="coordinacion.organizacion",
            ),
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "rol",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("coordinador", "Coordinador"),
                            ("campo", "Campo"),
                            ("lectura", "Lectura"),
                        ],
                        default="campo",
                        max_length=20,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
                (
                    "organizacion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="coordinacion.organizacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
