# Generated by Django 5.1.15 on 2026-06-27 23:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinacion', '0002_asignacion_idempotency_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('idempotency_key', models.UUIDField(unique=True)),
                ('original', models.FileField(blank=True, null=True, upload_to='fotos/orig/')),
                ('comprimida', models.FileField(blank=True, null=True, upload_to='fotos/comp/')),
                ('estado', models.CharField(choices=[('recibida', 'Recibida'), ('procesando', 'Procesando'), ('lista', 'Lista'), ('error', 'Error')], default='recibida', max_length=20)),
                ('bytes_original', models.PositiveIntegerField(blank=True, null=True)),
                ('bytes_comprimida', models.PositiveIntegerField(blank=True, null=True)),
                ('error_detalle', models.TextField(blank=True)),
                ('envio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fotos', to='coordinacion.envio')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
